### PR TITLE
Lucia improvements

### PR DESCRIPTION
**Pull request by Amerikranian**
The following things have been updated and or addressed since my issue was open.
1. Sound pool no longer accepts keep_pitch. It was broken and never quite worked anyways
2. Sound pool no longer singles out filename in the __init__ of the sound_item class and now uses kwargbs for everything.
3. Sound pool will no longer crash if an item was set to loop and the user provided an invalid sound path for said item. This fix should probably be redone at some point as it's a bit redundant, but hey.
4. Virtual input now has a capitalized class name.
5. Virtual input now uses kwargbs as the number of parameters keeps growing.
6. Virtual input now allows for the user to press escape to close itself.
7. the __init__ file has been updated with the plurals of key_pressed, key_released, key_down, and key_up functions. In addition, it also received a function called get_key_mods which is a wrapper over pygame.key.get_mods.
Everything has been tested on my machine and has ran successfully

### CODE REVIEW

**Comment by NicklasTegner** [comment]
Hi.

Nice work.
From what other code I've read and written, "**kwargs" is usually the standard name, not "**kwargbs", so if you could change that, to avoid confusion, it would be amazing.

**Comment by NicklasTegner** [comment]
Oalso: lucia/ui/virtualinput.py has merge issues, please update your fork with the latest changes and commit again :D

**Comment by Amerikranian** [comment]
I have updated **kwargbs to **kwargbs. My bad, I saw it written as kwargbs and it stuck with me.
I am not sure as to how to resolve the conflict with virtual input file. It seems like the conflict is in me changing the method to accept **kwargs, but if I undo this we will have 13 parameters again. If you could provide guidance as to the resolution that'd be great. I tried git fetch and it showed an m next to the virtualinput.py, but I'm not sure what I should do besides this.

**Comment by Amerikranian** [comment]
I figured it out, I apologize

**Pull request merged**
