### PR TITLE
Virtual input improvements

### PR DESCRIPTION
**Pull request by Amerikranian**
I have added the ability for the virtual input to have the user hold down keys. I have also provided the ability to toggle input to different character styles. Finally, I have added functions to ask the user for multiple messages of the same type, i.e, string and int. This addresses most of what the current open issue wants in regards to virtual input. Currently working on pressing control and jumping by words support, but that may not be for a while.

### CODE REVIEW

**Comment by NicklasTegner** [comment]
HI.
Nice work. I can see from the commits, that it also alters some stuff in the rotation module, since you haven't mentioned anything about it in the pr message, I'm asuming that it is a mistake

**Comment by Amerikranian** [comment]
I have just updated the branch and ensured that the rotation files match. Not sure what I need to do to make it show up on here... but yeh. Merging now should only change virtual input. Sorry about that.

**Comment by NicklasTegner** [comment]
You're good, when you push to your own fork, it shows up on here (look above your second message).
I'll look at it during the weekend (if no one else beets me to it) and merge it, when I've taken a look at it.

THanks for your hard work :)

**Comment by Amerikranian** [comment]
Ah. Thanks again. Sorry for the confusion. Let me know if anything needs clarification

**Comment by Amerikranian** [comment]
Hey.
Sorry for bringing this up, but I'm essentially stuck in regards to writing the tutorials for the engine until this gets resolved. A short update, even if it's something like we're still considering, would be nice.

**Comment by NicklasTegner** [comment]
Hi.
I have taken a look at it and it looks good. Sorry for taking so long 🥇

**Pull request merged**
